### ISSUE TITLE
firmware release hex?

### ISSUE THREAD

**Issue by abzman** [DuPAL-PAL-DUmper/DuPAL_Firmware#1]
I have tried to set this up by compiling optiboot for this processor and crystal, flashing that, then compiling the DuPAL code and flashing that but I can't seem to make it work.  Can you please put out one full hex file for the atmega328 and the fuse bit settings you used?

**Comment by hkzlab** [comment]
You can find the details on how to build optiboot and which fuses to set here: https://github.com/DuPAL-PAL-DUmper/DuPAL_Board

The firmware makefile contains the avrdude command to use to upload to the board via serial connection.

**Comment by abzman** [comment]
I think I've got it now, I'll let you know how it works
